baseURL = 'https://learn-make-teach.org/'
defaultContentLanguage = 'en'
title = 'Learn/Make/Teach'
[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en-US'
    weight = 1
  [languages.fr]
    languageName = 'Français'
    languageCode = 'fr-FR'
    weight = 2
